# Generated by Django 2.2.12 on 2020-06-08 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='weibo',
        ),
        migrations.RemoveField(
            model_name='user',
            name='zhihu',
        ),
        migrations.AddField(
            model_name='user',
            name='facebook',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Facebook链接'),
        ),
        migrations.AddField(
            model_name='user',
            name='google',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Google链接'),
        ),
        migrations.AlterField(
            model_name='user',
            name='linkedin',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Linkedin链接'),
        ),
    ]
