# Generated by Django 2.2.12 on 2020-05-29 14:26

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20200519_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='edited',
            field=models.BooleanField(default=False, verbose_name='是否已编辑'),
        ),
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='多个标签使用,(英文)隔开', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='标签'),
        ),
    ]
