# Generated by Django 2.2.12 on 2020-05-31 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20200529_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.CharField(blank=True, max_length=2048, null=True, verbose_name='文章图片'),
        ),
    ]
