# Generated by Django 2.2.12 on 2020-05-31 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
        ('articles', '0006_auto_20200531_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='im', to='upload.ArticleImage', verbose_name='文章图片'),
        ),
    ]
