# Generated by Django 2.2.12 on 2020-05-31 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_remove_article_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='image2',
            new_name='image',
        ),
    ]
