# Generated by Django 2.2.12 on 2020-05-18 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ('-created_at',), 'verbose_name': 'Home & News', 'verbose_name_plural': 'Home & News'},
        ),
    ]
