# Generated by Django 2.2.12 on 2020-05-21 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='qa.Question', verbose_name='问题'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='content_type',
            field=models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'qa'), ('model', 'answer')), models.Q(('app_label', 'qa'), ('model', 'question')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, related_name='votes_on', to='contenttypes.ContentType'),
        ),
    ]
