# Generated by Django 2.2.12 on 2020-06-02 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0002_auto_20200521_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='has_answer',
        ),
    ]
