# Generated by Django 2.2.12 on 2020-06-02 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0003_remove_question_has_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='status',
        ),
    ]
