# Generated by Django 2.2.12 on 2020-06-07 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_auto_20200607_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='verb',
            field=models.CharField(choices=[('L', 'liked'), ('C', 'commented on'), ('F', 'added to favorites'), ('A', 'answered'), ('W', 'accepted the answer'), ('R', 'replied to'), ('I', 'logged in'), ('O', 'logged out')], max_length=1, verbose_name='通知类别'),
        ),
    ]
